sudo: required
language: generic

services:
  - docker

before_install:
  - docker pull microsoft/azure-cli:2.0.31

script:
  - docker run --rm -e AZURE_SERVICEPRINCPIAL_KEY -e AZURE_SERVICEPRINCPIAL_ID -e AZURE_TENANTID -v $(pwd):/deploy microsoft/azure-cli:2.0.31 /bin/bash -c "az login --service-principal -u $AZURE_SERVICEPRINCPIAL_ID -p $AZURE_SERVICEPRINCPIAL_KEY --tenant $AZURE_TENANTID;az group deployment create -g MyTest --template-file /deploy/azuredeploy.json --parameters @/deploy/azuredeploy.parameters.json"
